name: WebdriverIO Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  wdio-tests:
    runs-on: ubuntu-latest
    container:
      image: node:18-bullseye-slim

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Chrome
        run: |
          apt-get update
          apt-get install -y wget gnupg
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add -
          sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
          apt-get update
          apt-get install -y google-chrome-stable xvfb

      - name: Install Node dependencies
        run: npm install

      - name: Run WebdriverIO Tests
        run: |
          export DISPLAY=:99
          Xvfb :99 -screen 0 1280x1024x24 &
          npm run local:test
